[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
goosy_vault = "5wsNMDzsM3RepTN9Z2A4DCJViqXE8o3KbFJfa3t5hmZh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cdhiraj40/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
goosy-vault-program-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/goosy-vault-program.ts"